apiVersion: v1
kind: Service
metadata:
  name: bluebikedata-api-server
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    port: 8001
    targetPort: 8001
  - name: "https"
    port: 8003
    targetPort: 8003
  selector:
    app: api-server