apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluebikedata-api-server
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      hostNetwork: true
      containers:
        - name: auth-svc
          image: gcr.io/cs3200-215502/auth-svc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              hostPort: 8000
        - name: api-svc
          image: gcr.io/cs3200-215502/api-svc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              hostPort: 8001
        # - name: live-data-svc
        #   image: gcr.io/cs3200-215502/live-data-svc:v1
        #   imagePullPolicy: Always
        #   ports:
        #     - containerPort: 8002
        #       hostPort: 8002
        - name: data-svc
          image: gcr.io/cs3200-215502/data-svc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
              hostPort: 8003