FROM nginx
EXPOSE 8080
COPY default.conf /etc/nginx/conf.d/default.conf
COPY src/index.html /usr/share/nginx/html/index.html
COPY src/dbproject.css /usr/share/nginx/html/dbproject.css
COPY src/dbproject.js /usr/share/nginx/html/dbproject.js