apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-svc
          image: gcr.io/cs3200-215502/nginx-svc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080